AllCops:
  EnabledByDefault: true

Bundler/GemComment:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Style/DocumentationMethod:
  Enabled: false

Style/Copyright:
  Enabled: false

Style/MethodCallWithArgsParentheses:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Lint/NumberConversion:
  Enabled: false
