AllCops:
  EnabledByDefault: true

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Style/DocumentationMethod:
  Enabled: false

Style/Copyright:
  Enabled: false

Lint/NumberConversion:
  Enabled: false