default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: admin
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: SignupAndLoginTemplateRails_development

test:
  <<: *default
  database: SignupAndLoginTemplateRails_test

production:
  url: <%= ENV['DATABASE_URL'] %>
